### ISSUE TITLE
Separate to different repos.

### ISSUE THREAD

**Issue by chhsiao1981** [ailabstw/go-pttai#244]
#### Version information:

Gptt
Version: 0.2.0
Git Commit: 33dac43efad52b7bdad5e475be77bddf609e27cd
Architecture: amd64
Go Version: go1.11.1

#### Type:

Enhancement

#### Description:

Currently we have all the components in the same repo, which is not good for long-term development.

We would like to separate the repo as follow:

* go-pttai:
    * cmd/gptt
    * ptthttp/
    * rpc/
     * content/
     * metrics/

* go-pttai-core: 
    * cmd/p2pbootnode
    * node/
    * p2p/
    * rlp/
    * common/
    * service/
    * user/
    * crypto/
    * event/
    * pttdb/
    * raft/
    * log/
    * account/
     * friend/

**Comment by poga** [comment]
https://github.com/ailabstw/go-pttai-core
