### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by poga** [ailabstw/go-pttai#251]
We specified GPLv3 in `LICENSE`. However, there're files with different license exist in the repo:

* files copied from `go-ethereum`: `LGPL`
* incorrect license: e.g. `cmd/bootnode/main.go`

**Comment by chhsiao1981** [comment]
I think it's better to follow ethereum setup:

For cmd: GPL
For non-cmd: LGPL

It means that:
1. any one who wants to use any part of non-cmd as lib and not modify the lib: It's ok to use it without LGPL, but need to claim the use of go-pttai as lib.
2. any one who wants to use any part of non-cmd as lib and modify the lib: the modified lib needs to follow LGPL, and claim the use of go-pttai as lib.
3. any one who uses any part of the cmd as part of their program: the program needs to be GPL compatible.

**Comment by poga** [comment]
About splitting core/non-core:

* core will be LGPL
* non-core will be switched to a permissive license, maybe apache v2?
