### ISSUE TITLE
Integrate pion/webrtc as another alternative p2p.

### ISSUE THREAD

**Issue by chhsiao1981** [ailabstw/go-pttai#258]
#### Version information:

Gptt
Version: 0.2.0
Git Commit: 33dac43efad52b7bdad5e475be77bddf609e27cd
Architecture: amd64
Go Version: go1.11.1
Operating System: linux

#### Type:

Enhancement

#### Description:

Currently we use libp2p as the underlying p2p-mechanism.

pion/webrtc looks great and is worth a try～

The following links may be a good start:

https://bloggeek.me/how-webrtc-works/
https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/
https://medium.com/@SergioPaniego/how-webrtc-works-internally-b4cf678c7587

#97

**Comment by backkem** [comment]
Some pointers:
- You may want to look at the [detach](https://github.com/pion/webrtc/tree/master/examples/data-channels-detach) example. This offers a more idiomatic API for sending data.
- We don't have a good example of using a signaling server yet. [This](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling) seems like a decent resource. We (pion) should probably create an example.
- If you want to set up your own STUN/TURN servers we also have one under pion/turn.
- Feel free to ask any questions or join our vibrant community [Slack](https://pion.ly/slack/).

**Comment by chhsiao1981** [comment]
another possibility is to use [ortc](https://github.com/pion/webrtc/blob/master/examples/ortc/main.go).

**Comment by chhsiao1981** [comment]
After preliminarily testing:

1. looks like able to reliably do udp-port-reuse on 5000.
2. there are other additional udp-ports created when creating a data-channel.

We will adopt the webrtc setup now.
Meanwhile, we will try to help pion/webrtc and eliminate the additional udp-port issue.

https://gist.github.com/chhsiao1981/d06d200ca010ac542b49b80a22e87b96

**Comment by backkem** [comment]
The other candidates are created here:
https://github.com/pion/stun/blob/e9c5388360b3a90b00af342e117c92e4e198de3b/client.go#L28
Which is called from:
https://github.com/pion/ice/blob/7245ac0866456f7c39a534f496d0f346ab7aad30/agent.go#L301
I'd like to avoid the port limitation logic in the stun package thought.

**Comment by chhsiao1981** [comment]
It looks like that current webrtc spec supports only 1-to-1 port conn.

One possible work-around for the p2p-over-webrtc is as follow:

1. There is a (cluster of) signal-server, using wss.
2. Initially, A and B connect to the signal-server using wss. The signal-server identifies the identity when initially connected.
3. When B would like to connect to A, B issue an offer, telling the signal-server that it's for A.
4. The signal-server tells A about the offer, A provides the answer to the signal-server.
5. The signal-server tells B the answer.
6. B connects with A.

**Comment by chhsiao1981** [comment]
Current status:

Implemented signal-server:

https://github.com/ailabstw/pttai-signal-server

TODO: integrate webrtc into p2p/server.go

**Comment by chhsiao1981** [comment]
Found that the process hangs if the size of the read-bytes < the size of the write-bytes.

https://gist.github.com/chhsiao1981/e054f6263b1c1b147bbc35076a7f93f2

We need some buffer in WebrtcConn to deal with this situation～

**Comment by poga** [comment]
Before jumping into solution, why does it hang?

**Comment by chhsiao1981** [comment]
It's blocked in datachannel.DataChannel.Read:

https://github.com/pion/datachannel/blob/master/datachannel.go#L169

which can be traced to sctp.Stream.ReadSCTP:

https://github.com/pion/sctp/blob/master/stream.go#L87

which can be traced to 

https://github.com/pion/sctp/blob/master/reassembly_queue.go#L246

reassembly_queue.read just continuously return error and stuck in the for loop in the stream.read if the size of the read-bytes is less than the size of the write-bytes.

**Comment by chhsiao1981** [comment]
After further testing,
the receiver just skips the msgs in which the size is larger than the size of the read-bytes, not resulting in deadlock.

we can view this as a feature rather than a bug.

We need to modify p2p/rlpx.go to fit in this feature though.

pion/webrtc#634

**Comment by chhsiao1981** [comment]
#271 closes this issue～
