### ISSUE TITLE
libp2p network issues

### ISSUE THREAD

**Issue by chhsiao1981** [ailabstw/go-pttai#97]
#### Version information:

Version: 0.1.0-unstable
Git Commit: b8de7e6bc861d23233dd4991df4586f1449ab79e
Architecture: amd64
Go Version: go1.10.4
Operating System: darwin

#### Type:

Enhancement

#### Description:

Currently we are using libp2p as the underlying p2p mechanism.

However, libp2p is still in the development stage, and it does not guarantee the success of the connections in the various network environment (ex: VPN).

We would like to know the connectivity under different network environment through this issue.

**Comment by chhsiao1981** [comment]
The new update in libp2p:

https://github.com/libp2p/go-libp2p/pull/490

**Comment by chhsiao1981** [comment]
nodes on linode can connect to nodes on digital ocean (both are with public ip)

**Comment by chhsiao1981** [comment]
Another possible p2p lib: https://github.com/anacrolix/torrent
(Torrent in go)

**Comment by chhsiao1981** [comment]
Another possible p2p lib: https://github.com/pions/webrtc
(webrtc in pure go)

**Comment by chhsiao1981** [comment]
https://github.com/libp2p/go-libp2p/issues/188

**Comment by chhsiao1981** [comment]
based on 

https://github.com/libp2p/go-libp2p/issues/375
https://gist.github.com/upperwal/38cd0c98e4a6b34c061db0ff26def9b9#file-libp2p_chat_bootstrapping-md

It's possible that we can have nat working by following the example.

**Comment by chhsiao1981** [comment]
We will firstly try the following setup for the libp2p-relay:

https://github.com/libp2p/go-libp2p-examples/blob/master/relay/main.go

**Comment by chhsiao1981** [comment]
issue with pions/webrtc pions-to-pions example:

requiring specifying true ip/port to connect to the peer.
need to check further how to do pions-to-pions across nat～

https://github.com/pion/webrtc/tree/master/examples/pion-to-pion

**Comment by chhsiao1981** [comment]
https://github.com/libp2p/specs/tree/master/relay

**Comment by backkem** [comment]
> issue with pions/webrtc pions-to-pions example:
> 
> requiring specifying true ip/port to connect to the peer.
> need to check further how to do pions-to-pions across nat～
> 
> https://github.com/pion/webrtc/tree/master/examples/pion-to-pion

Quick note: WebRTC doesn't require a specific port. It requires you to exchange some data ( An offer and the corresponding answer) in order to set up a connection. It is not specified how to exchange this information. You can copy/paste it, send it over a central server, ... . In the case of the pion to pion example we send this information it over a direct http connection but this is not required. It just makes the example easy to run.

**Comment by chhsiao1981** [comment]
@backkem 

Thank you so much for the explanation～
pion/webrtc is really awesome！

I am noob to webrtc,
but I would like to try to integrate pion/webrtc into this repo as an alternative option to libp2p～

**Comment by chhsiao1981** [comment]
After testing #257:

Given 1 relay-server,
It looks like it is with high probability that it takes some amount of time (possibly more than 3-mins) to init connection～
(node-1: nat behind mobile-Chung-Hua-Telecom, node-2: Digital-Ocean, relay-server: aws-singapore)

Would like to: 
1. dig further about libp2p discovery mechanism.
2. follow #258

**Comment by poga** [comment]
We had done switching to WebRTC in https://github.com/ailabstw/go-pttai/pull/271.
